AppSettings:
    DataStore:
        LLM_Platform:
            # mssql
            Server: "localhost"
            DatabaseName: "LLM_Plateform"
            UserName: "sa"
            Password: "your_password_foo"
            Port: 1433  # default port for MSSQL
    CORS:
        AllowedOrigins: ["*"]  # Allow all origins, or specify a list of domains (e.g., ["http://example.com"])


